### ISSUE TITLE
Checkboxes: slechts 1 selectie komt door

### ISSUE THREAD

**Issue by Theo-denBlanken** [TheExiledCat/Opdracht7#9]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
<label><input type="checkbox" name="TopPunt" value="HTML/CSS">HTML/CSS Markup</label>
      <label><input type="checkbox" name="TopPunt" value="Javascript">Javascript Code</label>
      <label><input type="checkbox" name="TopPunt" value="Samenwerking">Samenwerking</label>
      <label<input type="checkbox" name="TopPunt" value="Plannen">Plannen></label>
      <label><input type="checkbox" name="TopPunt" value="Java Programming">Programmeren in Java</label>
     
```

URL: https://github.com/TheExiledCat/Opdracht7/blob/master/index.html

Feedback: Omdat ze allemaal dezelfde name hebben.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"9d7d88c493999fc50c4c8c9518916cc9b9d032c9","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by TheExiledCat** [comment]
gefixt
